# Generated by Django 5.0.2 on 2024-02-27 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(default=0, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Ano',
                'verbose_name_plural': 'Anos',
            },
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Banca',
                'verbose_name_plural': 'Bancas',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/%Y/%m/%d/', verbose_name='PDF')),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d/', verbose_name='Vídeo')),
                ('foto', models.FileField(blank=True, null=True, upload_to='fotos_capa/%Y/%m/%d/', verbose_name='Capa')),
                ('visibilidade', models.BooleanField(default=True, verbose_name='Visibilidade')),
                ('nome', models.CharField(default='', max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(default='', max_length=10000, verbose_name='Descrição')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('A', models.CharField(max_length=2000, verbose_name='A')),
                ('B', models.CharField(max_length=2000, verbose_name='B')),
                ('C', models.CharField(max_length=2000, verbose_name='C')),
                ('D', models.CharField(max_length=2000, verbose_name='D')),
                ('E', models.CharField(max_length=2000, verbose_name='E')),
                ('gabarito_alternativa', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1, verbose_name='Gabarito Alternativa')),
                ('gabarito_texto', models.CharField(max_length=2000, verbose_name='Gabarito Texto')),
                ('visibilidade', models.BooleanField(default=True, verbose_name='Visibilidade')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.ano', verbose_name='Ano')),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.banca', verbose_name='Banca')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.disciplina', verbose_name='Disciplina')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.prova', verbose_name='Prova')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='QuestaoRespondida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('Acertei', 'Acertei'), ('Errei', 'Errei'), ('Pendente', 'Pendente')], default='Pendente', max_length=100, verbose_name='Resposta')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao', verbose_name='Questão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Questão Respondida',
                'verbose_name_plural': 'Questões Respondidas',
            },
        ),
    ]
