# Generated by Django 5.0.2 on 2024-02-28 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questoes.estado', verbose_name='Estado'),
        ),
    ]
