# Generated by Django 5.0.2 on 2024-02-28 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0003_questao_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questoes.estado', verbose_name='Estado'),
        ),
    ]
