# Generated by Django 5.0.2 on 2024-03-04 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0005_comentarios_duvidas_respostas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportarDuvidasProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', max_length=5000, verbose_name='Texto')),
                ('arquivo', models.FileField(blank=True, default=None, null=True, upload_to='reportar_duvidas_professor/%Y/%m/%d/', verbose_name='Arquivo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('visibilidade', models.BooleanField(default=True, verbose_name='Visibilidade')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao', verbose_name='Questão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Reportar Duvida Professor',
                'verbose_name_plural': 'Reportar Duvidas Professor',
            },
        ),
    ]
