# Generated by Django 5.0.2 on 2024-05-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0007_remove_duvidas_questao_remove_duvidas_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='A',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='B',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='C',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='D',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='E',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='E'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='gabarito_alternativa',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Correto', 'Correto'), ('Errado', 'Errado')], default='A', max_length=7, verbose_name='Gabarito Alternativa'),
        ),
    ]
