# Generated by Django 5.0.2 on 2024-05-06 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0008_alter_questao_a_alter_questao_b_alter_questao_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questoes.estado', verbose_name='Estado'),
        ),
    ]
