# Generated by Django 5.0.2 on 2024-05-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0009_alter_questao_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='video',
            field=models.URLField(max_length=10000, verbose_name='Link'),
        ),
    ]
