# Generated by Django 5.0.2 on 2024-05-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0010_alter_aula_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='foto',
        ),
    ]
