# Generated by Django 5.0.2 on 2024-02-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_recuperacaosenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperacaosenha',
            name='recuperacao',
            field=models.BooleanField(default=False, verbose_name='Foi Recuperado?'),
        ),
    ]
