# Generated by Django 5.0.2 on 2024-02-19 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_recuperacaosenha_recuperacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperacaosenha',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
