# Generated by Django 5.0.2 on 2024-02-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_planos_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='link_pagamento',
            field=models.URLField(default='', max_length=1000, verbose_name='Link de Pagamento'),
        ),
    ]
