# Generated by Django 5.0.2 on 2024-02-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_pedido_link_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('UNDEFINED', 'UNDEFINED'), ('CREDIT_CARD', 'CREDIT_CARD'), ('PIX', 'PIX'), ('BOLETO', 'BOLETO')], default='UNDEFINED', max_length=20, verbose_name='Método de Pagamento'),
        ),
    ]
