# Generated by Django 5.0.2 on 2024-02-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_alter_pedido_metodo_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='url_payment',
        ),
    ]
