# Generated by Django 5.0.2 on 2024-03-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_remove_pedido_url_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='idPlano',
        ),
        migrations.AddField(
            model_name='pedido',
            name='idPagamento',
            field=models.CharField(default='', max_length=255, verbose_name='idPagamento'),
        ),
    ]
