# Generated by Django 5.0.2 on 2024-03-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_remove_pedido_idplano_pedido_idpagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(auto_now=True, verbose_name='Data do pedido'),
        ),
    ]
