# Generated by Django 5.0.2 on 2024-03-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_alter_pedido_data_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='idAssinatura',
            field=models.CharField(default='', max_length=255, verbose_name='idAssinatura'),
        ),
    ]
