# Generated by Django 5.0.2 on 2024-03-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_pedido_idassinatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data_vencimento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Atualização'),
        ),
    ]
