# Generated by Django 5.0.2 on 2024-03-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_remove_pedido_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da Última Atualização'),
        ),
    ]
