# Generated by Django 5.0.2 on 2024-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_alter_pedido_data_ultima_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.FileField(blank=True, default=None, null=True, upload_to='fotos_perfis/%Y/%m/%d/', verbose_name='Foto'),
        ),
    ]
