# Generated by Django 5.0.2 on 2024-03-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='nome_plano_avancado',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Plano Avançado'),
        ),
        migrations.AddField(
            model_name='planos',
            name='nome_plano_basico',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Plano Básico'),
        ),
        migrations.AddField(
            model_name='planos',
            name='nome_plano_intermediario',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Plano Intermediário'),
        ),
    ]
