# Generated by Django 5.0.2 on 2024-03-31 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0017_topicos_planos_topicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planos',
            name='topicos',
        ),
        migrations.AddField(
            model_name='topicos',
            name='plano',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.planos', verbose_name='Planos'),
        ),
    ]
