# Generated by Django 5.0.2 on 2024-03-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0019_remove_planos_avancado_remove_planos_basico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planos',
            name='tipo',
            field=models.CharField(choices=[('basico', 'basico'), ('avancado', 'avancado'), ('intermediario', 'intermediario')], default='bacico', max_length=100, verbose_name='Tipo de Plano'),
        ),
    ]
