# Generated by Django 5.0.2 on 2024-04-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0020_planos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='tipo',
            field=models.CharField(choices=[('basico', 'basico'), ('avancado', 'avancado'), ('intermediario', 'intermediario')], default='basico', max_length=100, verbose_name='Tipo de Plano'),
        ),
    ]
