# Generated by Django 5.0.2 on 2024-02-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='', max_length=300, verbose_name='Título'),
        ),
    ]
