# Generated by Django 5.0.2 on 2024-02-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(default='', max_length=3000, verbose_name='Descrição'),
        ),
    ]
