# Generated by Django 5.0.2 on 2024-04-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SobreNos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('texto', models.TextField(max_length=1000000000, verbose_name='Texto')),
                ('video', models.FileField(upload_to='sobre_nos/%Y/%m/%d/', verbose_name='Vídeo')),
            ],
            options={
                'verbose_name': 'Sobre Nós',
                'verbose_name_plural': 'Sobre Nós',
            },
        ),
    ]
