# Generated by Django 5.0.2 on 2024-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobrenos',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='sobre_nos/%Y/%m/%d/', verbose_name='Capa'),
        ),
    ]
