# Generated by Django 5.0.2 on 2024-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_faleconosco'),
    ]

    operations = [
        migrations.AddField(
            model_name='faleconosco',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data'),
        ),
    ]
