# Generated by Django 5.0.2 on 2024-05-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faleconosco_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsProntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Email Pronto',
                'verbose_name_plural': 'Emails Prontos',
            },
        ),
    ]
