# Generated by Django 5.0.2 on 2024-05-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_emailsprontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsprontos',
            name='contagem',
            field=models.IntegerField(default=0, verbose_name='Contagem'),
        ),
    ]
