# Generated by Django 5.0.2 on 2024-05-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_emailsprontos_contagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsprontos',
            name='texto',
        ),
        migrations.AddField(
            model_name='emailsprontos',
            name='texto1',
            field=models.TextField(blank=True, null=True, verbose_name='Texto1'),
        ),
        migrations.AddField(
            model_name='emailsprontos',
            name='texto2',
            field=models.TextField(blank=True, null=True, verbose_name='Texto2'),
        ),
        migrations.AddField(
            model_name='emailsprontos',
            name='texto3',
            field=models.TextField(blank=True, null=True, verbose_name='Texto3'),
        ),
        migrations.AddField(
            model_name='emailsprontos',
            name='texto4',
            field=models.TextField(blank=True, null=True, verbose_name='Texto4'),
        ),
        migrations.AddField(
            model_name='emailsprontos',
            name='texto5',
            field=models.TextField(blank=True, null=True, verbose_name='Texto5'),
        ),
        migrations.AddField(
            model_name='emailsprontos',
            name='texto6',
            field=models.TextField(blank=True, null=True, verbose_name='Texto6'),
        ),
        migrations.AddField(
            model_name='emailsprontos',
            name='texto7',
            field=models.TextField(blank=True, null=True, verbose_name='Texto7'),
        ),
        migrations.AddField(
            model_name='emailsprontos',
            name='texto8',
            field=models.TextField(blank=True, null=True, verbose_name='Texto8'),
        ),
    ]
