# Generated by Django 5.0.2 on 2024-05-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_emailsprontos_texto_emailsprontos_texto1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Arquivo Excel',
                'verbose_name_plural': 'Arquivos Excel',
            },
        ),
    ]
